version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:latest
    container_name: my-container-postgres
    hostname: myhost
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 5432:5432
    
